# Generated by Django 4.0.3 on 2022-03-06 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('cost', models.CharField(max_length=10)),
                ('length', models.CharField(max_length=56)),
                ('languages', models.TextField()),
                ('etype', models.CharField(max_length=256)),
                ('erate', models.CharField(max_length=6)),
                ('internship', models.CharField(max_length=56)),
                ('loc', models.TextField()),
                ('desc', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
